<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Suku Cadang_sc-1hxhqap-3 btnGPj</name>
   <tag></tag>
   <elementGuidId>93b5d040-0738-440c-97ee-3b5102f5a7e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='app']/div/div/section/section/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3ff33680-6d96-473f-9f78-e58e67d406e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-1hxhqap-3 btnGPj</value>
      <webElementGuid>6dfcad03-dd78-49b4-880d-b8ff6028bffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;sc-1dze5zo-0 lnpKeT&quot;]/section[@class=&quot;sc-1dze5zo-1 imPRYC&quot;]/section[@class=&quot;sc-60zcpy-1 klCJsD&quot;]/div[@class=&quot;sc-1crxk01-0 ksZDNo sc-10b1rua-3 hRIagK&quot;]/div[@class=&quot;sc-1crxk01-0 gepUjx sc-1hxhqap-0 fFaRKu&quot;]/div[@class=&quot;sc-1hxhqap-3 btnGPj&quot;]</value>
      <webElementGuid>48ef023e-8b78-480d-9b62-425a9e693b6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app']/div/div/section/section/div/div[2]/div</value>
      <webElementGuid>5555d559-4bf4-4648-ab56-dad9ebd1d2cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suku Cadang'])[1]/following::div[2]</value>
      <webElementGuid>86a5954b-02f9-40c2-9f56-7ce4ae1ff812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Layanan Bengkel'])[1]/preceding::div[1]</value>
      <webElementGuid>b8393c3e-953c-4f0b-8f6f-8f3f9b6b98e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home Service'])[1]/preceding::div[2]</value>
      <webElementGuid>df380d7b-4697-4501-9ddc-260e5a2bb6b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div</value>
      <webElementGuid>28d4519c-a52d-4527-9cea-e2e2dfe1aea8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
