<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Lihat Semua_sc-1mpuug8-0 bJwxGO</name>
   <tag></tag>
   <elementGuidId>2153368d-4056-4c0e-b56c-aeda51fc06b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sc-1mpuug8-0.bJwxGO</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='app']/div/div/section/section/div[9]/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>58254581-a9c1-4699-aed7-790f06b33564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-1mpuug8-0 bJwxGO</value>
      <webElementGuid>eef3b28a-daf5-468d-a945-e93ad400137b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;sc-1dze5zo-0 lnpKeT&quot;]/section[@class=&quot;sc-1dze5zo-1 imPRYC&quot;]/section[@class=&quot;sc-60zcpy-1 klCJsD&quot;]/div[@class=&quot;sc-1s4q4ah-0 iYDIxM&quot;]/div[@class=&quot;sc-1crxk01-0 imebcy sc-1s4q4ah-1 bJabho&quot;]/div[@class=&quot;sc-1mpuug8-0 bJwxGO&quot;]</value>
      <webElementGuid>97785d83-eeb0-41ab-854f-33248c52c9b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app']/div/div/section/section/div[9]/div[2]/div[2]</value>
      <webElementGuid>49f48bf6-d72b-451c-b890-aad7991168be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div[2]</value>
      <webElementGuid>fffeaf28-4441-4146-ab19-a8b4a48a8e91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
