<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Alamat Email atau Nomor HP_sc-1auyczi_6f84f0</name>
   <tag></tag>
   <elementGuidId>802ef171-ec9c-46c8-a781-8320ae4a7d00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.sc-1auyczi-2.bIZmZe.sc-1uj1rn4-2.gFJWwS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>983f7cf1-acf3-4e05-a3f3-6c0ceccd96ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>71d11bcb-4eba-4ef8-aea7-00a0db3fb52a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f63a1b90-8771-4677-b766-f977654a999c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-1auyczi-2 bIZmZe sc-1uj1rn4-2 gFJWwS</value>
      <webElementGuid>23f4a3ca-29d4-4fb4-a004-8e7e208a9689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>new-password</value>
      <webElementGuid>8a3e8c02-7a47-4b3a-9891-041f67a2c870</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;sc-vswk66-0 fJiAhm&quot;]/div[@class=&quot;sc-rkmhgf-0 hWVtzq&quot;]/div[@class=&quot;sc-1crxk01-0 gVKylD&quot;]/div[@class=&quot;sc-1crxk01-0 kllYhf&quot;]/div[@class=&quot;sc-1crxk01-0 inhaeL&quot;]/div[@class=&quot;sc-1uj1rn4-3 iuAPRv&quot;]/input[@class=&quot;sc-1auyczi-2 bIZmZe sc-1uj1rn4-2 gFJWwS&quot;]</value>
      <webElementGuid>cdfbe944-9128-4cb0-85b7-c723e68182c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>9c34452b-049c-4364-9823-801107a32c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='app']/div/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>54849960-eafd-414c-a5be-75bb7f907560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>f171f20c-8356-408e-843a-200a12be4877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>3abe08e7-15c0-44e8-b155-b05527dae2a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
